version: '3.1'

services:

  web:
    image: nginx
    volumes:
    - ./my-site:/usr/share/nginx/html
    ports:
    - "8080:80"
  ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'web:80'
